import { spawn } from 'node:child_process'
import { createWriteStream } from 'node:fs'
import { readFile, writeFile, mkdir } from 'node:fs/promises'
import { createHash } from 'node:crypto'

// Run every check, preserving each real exit status even when an earlier check fails.
const routed = process.argv.includes('--routed')
const verifiedInputPaths = ['index.circuit.tsx', 'board-markings.tsx', 'feature-parity.tsx', 'mounting-template.svg', 'package.json', 'hardware-contract.json', 'board-standards.json', 'routing/requirements.json', 'tscircuit.config.json']
async function hashInputs() {
  return Object.fromEntries(await Promise.all(verifiedInputPaths.map(async (path) => [path, createHash('sha256').update(await readFile(path)).digest('hex')])))
}
const inputsBefore = await hashInputs()
const checks = [
  ['toolchain', ['run', 'check:toolchain']],
  ['cloud-package', ['run', 'check:cloud-package']],
  ['mounting-template', ['run', 'check:mounting-template']],
  ['typecheck', ['run', 'typecheck']],
  ['firmware-pins', ['run', 'check:firmware-pins']],
  ['firmware', ['run', 'check:firmware']],
  ['preview', ['run', 'build:preview']],
  ['feature-parity', ['run', 'check:feature-parity']],
  ['normalize-svgs', ['run', 'normalize:svgs']],
  ['script-catalog', ['run', 'check:script-catalog']],
  ['topology-tests', ['test', 'scripts/design.test.mjs', 'scripts/via-net-identity.test.mjs']],
  ['netlist', ['run', 'check:netlist']],
  ['schematic', ['run', 'check:schematic']],
  ['placement', ['run', 'check:placement']],
  ['routing-difficulty', ['run', 'check:routing']],
  ['decoupling', ['run', 'check:decoupling']],
  ['assembly', ['run', 'check:assembly']],
  ['board-standards', ['run', 'check:standards']],
  ['local-copper', ['run', 'check:local-copper']],
  ['shorts', ['run', 'check:shorts']],
  ...(routed ? [['kicad-drc', ['run', 'check:kicad-drc']]] : []),
  ...(routed ? [['power-routing', ['run', 'check:power-routing']]] : []),
  ...(routed ? [['routing-fingerprint', ['run', 'check:routing-fingerprint']]] : []),
]
await mkdir('docs/checks', {recursive: true})
const results=[]
for (const [name,args] of checks) {
  const log=`docs/checks/${name}.log`
  const started=Date.now()
  const exit_code=await new Promise((resolve,reject)=>{
    const stream=createWriteStream(log)
    const child=spawn('bun',args,{stdio:['ignore','pipe','pipe']})
    child.stdout.pipe(stream,{end:false});child.stderr.pipe(stream,{end:false})
    child.on('error',reject)
    child.on('close',code=>stream.end(()=>resolve(code ?? 1)))
  })
  results.push({name,exit_code,status:exit_code===0?'pass':'fail',seconds:(Date.now()-started)/1000,log})
  console.log(`${name}: ${exit_code===0?'PASS':'FAIL'} (${log})`)
}
const data=JSON.parse(await readFile('dist/index/circuit.json'))
const inputsAfter = await hashInputs()
const changedInputs = verifiedInputPaths.filter((path) => inputsBefore[path] !== inputsAfter[path])
await writeFile('docs/checks/input-stability.log', changedInputs.length ? `Changed during validation:\n${changedInputs.join('\n')}\n` : 'Verified inputs remained unchanged during validation.\n')
results.push({name:'input-stability',exit_code:changedInputs.length?1:0,status:changedInputs.length?'fail':'pass',seconds:0,log:'docs/checks/input-stability.log'})
console.log(`input-stability: ${changedInputs.length?'FAIL':'PASS'} (docs/checks/input-stability.log)`)
const counts={}
for(const row of data) if(row.type.endsWith('_error')||row.type.endsWith('_warning')) counts[row.type]=(counts[row.type]||0)+1
const report={
  checked_at:new Date().toISOString(),
  entry_sha256:inputsBefore['index.circuit.tsx'],
  verified_inputs:inputsBefore,
  source_changed_during_validation:changedInputs,
  model:routed?'source checks plus externally routed KiCad PCB verification':'routing-disabled review preview',
  checks:results,
  circuit_messages:counts,
  routed_board_verified:routed && results.every(r=>r.exit_code===0),
  prototype_fabrication_orderable:routed && results.every(r=>r.exit_code===0),
  production_released:false,
  limitations:[
    'The KiCad DRC proves geometric connectivity under the committed project rules; it does not replace physical validation.',
    'Placement and schematic CLI checks include advisory heuristics; their nonzero exit codes are retained.',
    'Stock is a separate timestamped check in stock-report.json, not reserved assembly inventory.',
    'See routing-report.json for the final route record and release-status.json for hardware/firmware gates.'
  ]
}
await writeFile('docs/verification.json',JSON.stringify(report,null,2))
const verificationMarkdown = `# PD1180-EPR verification\n\n` +
  `Validated **${report.checked_at}** against the pinned local toolchain. This summary is generated by \`bun run verify\`; machine-readable results remain in [docs/verification.json](docs/verification.json).\n\n` +
  `| Check | Result | Time | Evidence |\n|---|---:|---:|---|\n` +
  results.map((result) => `| ${result.name} | ${result.status.toUpperCase()} | ${result.seconds.toFixed(1)} s | \`${result.log}\` |`).join('\n') +
  `\n\n- Routed KiCad board verified: **${report.routed_board_verified ? 'yes' : 'no'}**\n` +
  `- Prototype fabrication orderable: **${report.prototype_fabrication_orderable ? 'yes' : 'no'}**\n` +
  `- Production released: **no**\n` +
  `- Verified entry SHA-256: \`${report.entry_sha256}\`\n\n` +
  `Production remains gated by the TI PD image, STM32 target firmware, brake/load sizing, magnet alignment and powered thermal/EMC validation. See [docs/release-status.json](docs/release-status.json).\n`
await writeFile('verification.md', verificationMarkdown)
if(results.some(r=>r.exit_code!==0)||Object.keys(counts).some(k=>k.endsWith('_error')))process.exitCode=1
