// Generated by scripts/generate-motor-assembly.mjs; immutable model URLs and hashes are recorded in engineering/mechanical/assembly.json.
export const MOTOR_GLB = "https://raw.githubusercontent.com/techmannih/pd1180-epr/f7d74d3f20d73caa22ff136048b776b680c9abc1/engineering/mechanical/34hs31-6004s1.glb"
export const MOTOR_FIXTURE_GLB = "https://raw.githubusercontent.com/techmannih/pd1180-epr/f7d74d3f20d73caa22ff136048b776b680c9abc1/engineering/mechanical/adapter-proposal.glb"
export const MOTOR_REAR_Z = -10.8
