[platformio]
src_dir = .
include_dir = include
boards_dir = boards

[env:pd1180]
platform = ststm32@20.0.0
platform_packages =
  platformio/framework-arduinoststm32@4.30000.0
  platformio/toolchain-gccarmnoneeabi@1.120301.0
  platformio/framework-cmsis@2.60300.0
  platformio/framework-cmsis-dsp@1.16.2
  platformio/tool-scons@4.40801.0
board = pd1180
framework = arduino
upload_protocol = stlink
build_src_filter = +<src/control.c> +<src/telemetry.c> +<src/pd_contract.c> +<src/tmc5160_config.c> +<target/*.cpp>
build_flags =
  -D PIO_FRAMEWORK_ARDUINO_ENABLE_CDC
  -D USBCON
  -D USBD_USE_CDC
  -D USBD_SELF_POWERED=0
  -D USBD_MAX_POWER=250
  -D HAL_IWDG_MODULE_ENABLED
  -D SERIAL_RX_BUFFER_SIZE=128
  -D SERIAL_TX_BUFFER_SIZE=128
  -D I2C_TIMEOUT_TICK=5
  -D SPI_TIMEOUT=5
